name: Docker Build and Run

on:
  pull_request:
    branches: ['main']

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check workspace and grant permission
        run: echo ${{ github.workspace }}; ls -la ${{ github.workspace }}; chmod +x entrypoint.sh

      - name: Build Docker image
        run: docker build -t robotparser:latest_ci .

      - name: List input files
        run: ls -1 samples/input/*.xml > input_files.txt

      - name: Run Docker container for each input file
        run: |
          while IFS= read -r input_file; do
            docker run --name ci_for_robotparser --rm -v ${{ github.workspace }}:/app robotparser:latest_ci -i "/app/${input_file}" -o "/app/samples/generated_output/$(basename ${input_file} .xml).json"
          done < input_files.txt

      - name: Archive JSON artifacts
        uses: actions/upload-artifact@v4.3.0
        with:
          name: json-artifacts
          path: samples/generated_output/*.json